services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './config.hjson:/config.hjson:ro'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  parser:
    driver: local
  postgres:
    driver: local
